const RECEIPT_PAYMENT = {
    PROCESS:{
        receiveMenu: ["Phiếu thu", "Thu tiền theo hóa đơn", "Thu tiền theo hóa đơn nhiều khách hàng"],
        paymentMenu: [
            "Phiếu chi", 
            "Trả tiền theo hóa đơn",
            "Nộp thuế",
            "Nộp bảo hiểm",
            "Trả lương"
        ],
        auditMenu: ["Kiểm kê"]
    },

    contentDelete: "Bạn có muốn xóa chứng từ <",
    contentDeleteMultiple: "Bạn có muốn xóa những chứng từ này không?",
    FILE_NAME: "Thu_Chi_Tien_Mat",

    LIST_RECEIPT:{
        totalReceive: "Tổng thu đầu năm đến hiện tại",
        totalPayment: "Tổng chi đầu năm đến hiện tại",
        fundBalance: "Tồn quỹ hiện tại",
        figureUpTo: "Số liệu tính đến: 7h35",
        moneyOne: "0,00",
        moneyTwo: "1.948.714.501,00",
        note: "Ghi sổ",
        unNote: "Bỏ ghi",
        duplicate: "Nhân bản",
        nextYearPresent: "Đầu năm tới hiện tại",
        receive: "Thu tiền",
        payment: "Chi tiền",
        paymentV2: "Phiếu chi",
        payByBill: "Trả tiền theo hóa đơn",
        taxPayer: "Nộp thuế",
        submitInsurance: "Nộp bảo hiểm",
        paySalary: "Trả lương",
        tableHeader: {
            accountingDate: "Ngày hạch toán",
            receiptDate: "Ngày chứng từ",
            receiptNumber: "Số chứng từ",
            numberMoney: "Số tiền",
            reason: "Diễn giải",
            obj: "Đối tượng",
            codeObj: "Mã đối tượng",
            address: "Địa chỉ",
            feature: "Chức năng",
        },
        view: "Xem",
        total: "Tổng",
        freeText: {
            all: "Tất cả",
            optionReceipt: ["Tất cả", "Phiếu thu", "Phiếu chi"],
            numberReceiptHandle: "Số chứng từ được xử lí:",
            numberReceiptSuccess: "Số chứng từ thành công:",
            numberReceiptNotSuccess: "Số chứng từ không thành công:",
            recetptNoted: "Các chứng từ sau đã được ghi sổ:",
            pleaseCheck: "vui lòng kiểm tra lại.",
            titleResultHandleReceipt: "Kết quả xóa chứng từ", 
            unNoteSuccess: "Bỏ ghi sổ thành công"
        }
    },

    FORM_PAYMENT:{
        receiptProperty: [
            "ProviderId",
            "ProviderCode",
            "ProviderName",
            "ReceiveName",
            "Address",
            "Reason",
            "EmployeeId",
            "FullName",
            "QuantityAttach",
            "AccountingDate",
            "ReceiptDate",
            "ReceiptNumber",
            "AccountDebtId",
            "AccountBalanceId",
        ],
        optionHeader: [
            "1. Trả tiền nhà cung cấp (không theo hóa đơn)",
            "2. Tạm ứng cho nhân viên",
            "3. Chi mua ngoài có hóa đơn",
            "4. Trả lương nhân viên",
            "5. Chuyển tiền cho chi nhánh khác",
            "6. Gửi tiền vào ngân hàng",
            "7. Chi khác"
        ],
        textProperty:{
            providerCode: "Mã nhà cung cấp",
            headerCBBProvider: ['Đối tượng', 'Tên đối tượng', 'Mã số thuế', 'Địa chỉ', 'Điện thoại'],
            bodyCBBProvider: ['ProviderCode', 'ProviderName', 'TaxCode', 'Address', 'PhoneNumber'],
            providerName: "Tên nhà cung cấp",
            receive: "Người nhận",
            address: "Địa chỉ",
            reason: "Lí do chi",
            employee: "Nhân viên",
            headerCBBEmployee: ['Mã nhân viên', 'Tên nhân viên', 'Đơn vị', 'ĐT di động'],
            bodyCBBEmployee: ['EmployeeCode', 'FullName', 'DepartmentName', 'PhoneNumber'],
            attach: "Kèm theo",
            receiptRoot: "Chứng từ gốc",
            referrence: "Tham chiếu",
            accountingDate: "Ngày hạch toán",
            receiptDate: "Ngày phiếu chi",
            receiptNumber: "Số phiếu chi",
            totalMoney: "Tổng tiền",
            accountant: "Hạch toán",
            Description: "Diễn giải",
            accountDebt: "TK nợ",
            titleAccountDebt: "Tài khoản nợ",
            accountBalance: "TK có",
            titleAccountBalance: "Tài khoản có",
            numberMoney: "Số tiền",
            addRow: "Thêm dòng",
            deleteAllRow: "Xóa hết dòng",
            ghim: "Đính kèm",
            maxMemory: "Dung lượng tối đa 5MB",
            acctionFile: "Kéo/thả tệp vào đây hoặc bấm vào đây",
            btnCancel: "Hủy",
            btnSave: "Cất",
            btnSaveAndAdd: "Cất và Thêm",
            btnPrint: "In",
            btnUtiliti: "Tiện ích",
            btnEdit: "Sửa",
            btnNote: "Ghi sổ",
            btnEditQuick: "Sửa nhanh",
            btnUnNote: "Bỏ ghi",
        },
        receipt: "Phiếu chi",
        guide: "Hướng dẫn",
        titleIcon:{
            setting: "Tùy chỉnh giao diện",
            question: "Giúp (F1)",
            close: "Đóng (ESC)",
        },
        exist_pre: "Số chứng từ <",
        exist_end: "> đã tồn tại. Bạn có muốn chương trình tự động tăng số chứng từ không?",

        validateNotNull: {
            "ReceiptNumber": "Số phiếu chi không được để trống.",
            "AccountingDate": "Ngày hạch toán không được để trống.",
            "ReceiptDate": "Ngày phiếu chi không được để trống.",
            "AccountDebt": "Tài khoản nợ không được để trống.",
            "AccountBalance": "Tài khoản có không được để trống.",
            "Accountant": "Bạn phải nhập chứng từ chi tiết.",
        },

        maxLength:{
            "ReceiptNumber": {Limit: 20, Warning : "Số phiếu chi tối đa 20 kí tự."},
            "ProviderName": {Limit: 255, Warning : "Tên nhà cung cấp tối đa 255 kí tự."},
            "ReceiveName": {Limit: 100, Warning : "Người nhận tối đa 100 kí tự."},
            "Address": {Limit: 255, Warning : "Địa chỉ tối đa 255 kí tự."},
            "Reason": {Limit: 255, Warning : "Lí do chi tối đa 255 kí tự."},
        },
        freeText: {
            defaultReason: "Chi tiền cho",
            providerCode: "Mã nhà cung cấp",
            notExistInSystem: "không tồn tại trong hệ thống.",
            employee: "Nhân viên",
            accountDebt: "Tài khoản nợ",
            accountBalance: "Tài khoản có",
            notFolowProvider: "không theo nhà cung cấp, vui lòng kiểm tra lại.",
            detailFolowProvider: "chi tiết theo <Nhà cung cấp>, chứng từ hạch toán thiếu <Nhà cung cấp>.",
            noteNotSuccess: "Ghi sổ không thành công",
            noteSuccess: "Ghi sổ thành công",
        }
    },
}

export default RECEIPT_PAYMENT;